contextPath: /Customer-svc
spring:
  application:
    name: Customer-svc
  datasource:
    url: ${DB_URL:jdbc:mysql://192.168.1.11:3306/customer_svc?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    show-sql: true
flyway:
  enabled: true
  locations: classpath:/db/migration
  schemas: customer_svc
server:
  port: ${SERVER_PORT:9093}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SVC_DISCOVERY:http://user:password@localhost:9091/eureka/}
---
spring:
  profiles: test
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/customer_svc?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true